### ISSUE TITLE
App not starting with Multidex build enabled

### ISSUE THREAD

**Issue by sushant-j** [NativeScript/sample-Android-Multidex#2]
I recently ran into failing Android builds as mentioned [here](https://github.com/telerik/nativescript-ui-feedback/issues/417). One of the solutions provided was Multidex builds, and I landed on this repo. When I try to run this sample app though, it crashes with following errors:

```
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.multiDexingDemo/com.tns.MyActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'Method10001' of undefined
System.err: File: "/data/data/org.nativescript.multiDexingDemo/files/app/MyActivity.js, line: 21, column: 46
System.err: StackTrace: 
System.err: 	Frame: function:'android.app.Activity.extend.onCreate', file:'/data/data/org.nativescript.multiDexingDemo/files/app/MyActivity.js', line: 21, column: 47
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
System.err: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:148)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'Method10001' of undefined
System.err: File: "/data/data/org.nativescript.multiDexingDemo/files/app/MyActivity.js, line: 21, column: 46
System.err: StackTrace: 
System.err: 	Frame: function:'android.app.Activity.extend.onCreate', file:'/data/data/org.nativescript.multiDexingDemo/files/app/MyActivity.js', line: 21, column: 47
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:712)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:693)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:683)
System.err: 	at com.tns.MyActivity.onCreate(MyActivity.java:13)
System.err: 	at android.app.Activity.performCreate(Activity.java:6259)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
System.err: 	... 9 more
ActivityManager: Process org.nativescript.multiDexingDemo (pid 8906) has died
ActivityManager: cleanUpApplicationRecord -- 8906
^Csushant@HAL2000:~/ns-projects/sample-Android-Multidex$ tns run android
Searching for devices...
Skipping prepare.
Refreshing application...
Successfully synced application org.nativescript.multiDexingDemo on device ZY2232FSX5.
ActivityManager: Start proc 9120:org.nativescript.multiDexingDemo/u0a103 for activity org.nativescript.multiDexingDemo/com.tns.MyActivity
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.multiDexingDemo/com.tns.MyActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'Method10001' of undefined
System.err: File: "/data/data/org.nativescript.multiDexingDemo/files/app/MyActivity.js, line: 21, column: 46
System.err: StackTrace: 
System.err: 	Frame: function:'android.app.Activity.extend.onCreate', file:'/data/data/org.nativescript.multiDexingDemo/files/app/MyActivity.js', line: 21, column: 47
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
System.err: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:148)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'Method10001' of undefined
System.err: File: "/data/data/org.nativescript.multiDexingDemo/files/app/MyActivity.js, line: 21, column: 46
System.err: StackTrace: 
System.err: 	Frame: function:'android.app.Activity.extend.onCreate', file:'/data/data/org.nativescript.multiDexingDemo/files/app/MyActivity.js', line: 21, column: 47
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:712)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:693)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:683)
System.err: 	at com.tns.MyActivity.onCreate(MyActivity.java:13)
System.err: 	at android.app.Activity.performCreate(Activity.java:6259)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
System.err: 	... 9 more
ActivityManager: Process org.nativescript.multiDexingDemo (pid 9120) has died
ActivityManager: cleanUpApplicationRecord -- 9120
```

Am I missing any steps in running this sample app? I was planning to quickly check how multidex builds work and replicate same on my project. But since this app is not working (neither generating multiple .dex files), I'm confused if this technique works. 
Any help highly appreciated! Thanks :) 

Extra info if needed:
**Progress NativeScript UI version:** 3.2.0
**CLI**: 3.3.1 (Tried with CLI version 3.3.0 earlier, same issue.)
**Cross-platform modules**: 3.3.0
**Runtime(s)**: 3.3.1 for Android

**Comment by sushant-j** [comment]
Update: I tried commenting method call to Method10001, as I noted the following error log:
``` 
System.err: TypeError: Cannot read property 'Method10001' of undefined
```
Now the build passes, and app gets launched. I inspected the generated .apk and it does have 2 .dex files as the README.md says. 

It'd be really great if this repo provides instructions on how to go about making these changes on another {N} project though. 

I'd be happy to send a PR for the same if needed :)

**Comment by Plamen5kov** [comment]
@sushant-j feel welcome to send us a PR with improvements in the documentation.

>It'd be really great if this repo provides instructions on how to go about making these changes on another {N} project though.

This repo is not the right place for explaining general problems. Better add this info in the docs, so it's easily reachable.

**Comment by petekanev** [comment]
@sushant-j the README mentions running a node script in order to artificially generate a large class, so as to normally cause a dex overflow if not handled using multidex - https://github.com/NativeScript/sample-Android-Multidex/blob/master/README.md#how-to-build-and-test.

The sample itself is very simple and minimalistic - it does not even use the cross-platform modules. Instructions on getting up and running with multidex can be read in the official Android Dev documentation - https://developer.android.com/studio/build/multidex.html The sample covers cases where applications would be run on devices API 20 and lower.

In short it is done in 3 simple steps - 
 - modify the app.gradle to include the multidex library - https://github.com/NativeScript/sample-Android-Multidex/blob/master/app/App_Resources/Android/app.gradle
 - extend the `application` class and 'install' multidexing during app startup - https://github.com/NativeScript/sample-Android-Multidex/blob/c1f0335970cdcfc587bdfa3af47e6ab9514671a1/app/MultiDexApp.js#L6
 - register the extended application class in the AndroidManifest.xml - https://github.com/NativeScript/sample-Android-Multidex/blob/c1f0335970cdcfc587bdfa3af47e6ab9514671a1/app/App_Resources/Android/AndroidManifest.xml#L22

Feel free to contribute to our official documentation with a well-structured article. 

Thanks!

**Comment by sushant-j** [comment]
@Plamen5kov - Yes, you are right. I'll add submit a PR over the weekend on {N} docs.

@Pip3r4o - The steps you highlighted are exactly the ones I followed. I got it working, but had to look for this info at multiple places, which took some time. I'll try and submit a well-structured doc with all the above links and explanations as PR over the weekend.

Thanks for your feedback though guys :)

**Comment by Plamen5kov** [comment]
We'll be working in the future to make these steps happen seamlessly and provide better tools to control the gradle configuration.
